//
//  ExportConfiguration.swift
//  HealthKitDataGenerator
//
//  Created by Michael Seemann on 16.10.15.
//
//

import Foundation
import HealthKit

// MARK: - Export Types

/// What data should be exported
public enum HealthDataToExportType : String {
    /// all that is accessible
    case ALL                    = "All"
    /// only those that were written by the app
    case ADDED_BY_THIS_APP      = "Added by this app"
    /// only those that were generated by the app
    case GENERATED_BY_THIS_APP  = "Generated by this app"

    /// returns all values of this enumeration
    public static let allValues = [ALL, ADDED_BY_THIS_APP, GENERATED_BY_THIS_APP];
}

// MARK: - Export Configuration Protocol

/// Description of what should be exported.
public protocol ExportConfiguration {
    /// what should be exported - see HealthDataToExportType
    var exportType:HealthDataToExportType {get}
    /// the name of the profile
    var profileName:String {get}
    /// should uuids be exported or not
    var exportUuids:Bool {get}
    /// export start date
    var startDate:Date {get}
    /// export end date
    var endDate:Date {get}
    /// should authorize HK parameters from user or not
    var shouldAuthorize:Bool {get}
}

// MARK: - Export Configuration Extension

// possible configuration extension:
// export correlations even if they are present in the correlation type section
// export endDate always - even if the endDate and startDate are the same

internal extension ExportConfiguration {

    func getPredicate() -> NSPredicate? {

//        let predicateNoCorrelation = HKQuery.predicateForObjectsWithNoCorrelation()
        //let predicateNoCorrelation = HKQuery.predicateForSamples(withStart: Calendar.current.startOfDay(for: Date().addingTimeInterval(-60 * 60 * 23)),end: Calendar.current.startOfDay(for: Date()),options: .strictEndDate)
        let predicateNoCorrelation = HKQuery.predicateForSamples(withStart: startDate, end: endDate, options: .strictEndDate)

        switch exportType {
        case .ALL:
            return predicateNoCorrelation
        case .ADDED_BY_THIS_APP:
            return NSCompoundPredicate(andPredicateWithSubpredicates: [predicateNoCorrelation, HKQuery.predicateForObjects(from: HKSource.default())])
        case .GENERATED_BY_THIS_APP:
            return NSCompoundPredicate(andPredicateWithSubpredicates: [predicateNoCorrelation, HKQuery.predicateForObjects(withMetadataKey: "GeneratorSource", allowedValues: ["HSG"])])
        }
    }
}

// MARK: - Concrete Export Configuration

/// Export the whole Data from first Entry up to the current Date. E.g. full means the whole period of time.
public struct HealthDataFullExportConfiguration : ExportConfiguration {

    /// what should be exported - see HealthDataToExportType
    public var exportType = HealthDataToExportType.ALL // required
    /// the name of the profile
    public var profileName: String // required
    /// should uuids be exported or not
    public var exportUuids = false

    public var startDate: Date // required

    public var endDate: Date // required

    public var shouldAuthorize: Bool // required

    /// Instantiate a HealthDataFullExportConfiguration.
    /// - Parameter profileName: the name of the profile
    /// - Parameter exportType: what should be exported. see HealthDataToExportType
    public init(profileName:String, exportType: HealthDataToExportType, startDate: Date, endDate: Date, shouldAuthorize: Bool){
        self.profileName = profileName
        self.exportType = exportType
        self.startDate = startDate
        self.endDate = endDate
        self.shouldAuthorize = shouldAuthorize
    }
}

